source 'https://rubygems.org'

ruby '2.0.0'

gem 'rails', '4.0.1'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jquery-ui-rails', '~> 4.0.5'
gem 'jbuilder', '~> 1.2'
gem 'thin', '>= 1.6.0'
gem 'omniauth', '>= 1.1.4'
gem 'omniauth-github', '>= 1.1.1'
gem 'authority', '>= 2.9.0'
gem 'rolify', '>= 3.2.0'
gem 'bootstrap-sass', github: 'thomas-mcdonald/bootstrap-sass'
gem 'font-awesome-rails', '>= 4.0.3.0'
gem 'mongoid', github: 'mongoid/mongoid'
gem 'haml-rails'
gem 'simple_form'
gem 'draper'
gem 'angularjs-rails', '~> 1.2.0'
gem 'dotenv-rails'
gem 'active_model_serializers', '~> 0.8.1'
gem 'backbone-on-rails', '~> 1.1.0.0'

group :production do
  gem 'rails_12factor'
end

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'awesome_print'
  gem 'colored'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'database_cleaner'
  gem 'mongoid-rspec'
  gem 'jasminerice', github: 'bradphelan/jasminerice'
end
